default:
  Addr: project.dodream.wang:6379
  Password: "dolphin"
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 100
  PoolTimeout: 240s
  EnableTrace: true